{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "cloudbeaver.fullname" . }}.{{ .Release.Namespace }}
  namespace: {{ .Values.virtualService.istioNamespace }}
  labels:
    {{- include "cloudbeaver.labels" . | nindent 4 }}
spec:
  hosts:
  {{- range .Values.virtualService.domainNames }}
  - {{ . }}
  {{- end }}
  gateways:
  {{- range .Values.virtualService.istioGateways }}
  - {{ . }}
  {{- end }}
  http:
  - route:
    - destination:
        host: {{ include "cloudbeaver.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}

{{- end }}