apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  stream-config.conf: |
    {{ .Values.stremServerBlock | nindent 4 }}
---

{{- if .Values.extraEnv }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}-envs
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.extraEnv | nindent 2 }}
{{- end }}