apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
# ---

---
{{- if .Values.extraSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nginx.fullname" . }}-env
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $val := .Values.extraSecret }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end -}}
{{- end }}
