apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- range  .Values.pgPort  }}
    - port: {{ . }}
      targetPort: http
      protocol: TCP
      name: "http-{{ . }}"
    {{- end }}
  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
