apiVersion: v2
name: caddy
description: |
  The Caddy web server is an extensible, cross-platform, open-source web server written in Go.
type: application
version: 0.7.2
# renovate: image=caddy
appVersion: "2.11.3"
icon: https://i.imgur.com/c5DPgf7.png
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Bumped version from 2.11.2 to 2.11.3
  artifacthub.io/links: |
    - name: Caddy home
      url: https://github.com/caddyserver/caddy
    - name: Helm Repo
      url: https://gitlab.com/alexander-chernov/helm/caddy
